/*
** This file generated automatically from push.skeleton
*/

#include "defs.h"



static char const * const language[] =
{
    "#line 1 \"push.skeleton\"",
    "C",
    "",
    0
};

/* -*- C -*-

   The banner used here should be replaced with an #ident directive if
   the target C compiler supports #ident directives.

   If the skeleton is changed, the banner should be changed so that
   the altered version can easily be distinguished from the original.
*/

static char const * const banner[] =
{
    "#line 14 \"push.skeleton\"",
    "/*",
    "**    \"@(#)push.skel, based on byacc 1.8 (Berkeley) 01/20/91\";",
    "*/",
    "#define YYBTYACC 1",
    "",
    "",
    "",
    "/* [i_a] */",
    "#ifndef HAS_MSVC_2005_ISO_RTL",
    "#if defined(_MSC_VER)",
    "#if _MSC_VER >= 1400 /* VS.NET 2005 or above: 'fix' those deprecated functions */",
    "#define HAS_MSVC_2005_ISO_RTL     1",
    "#endif",
    "#endif",
    "",
    "#ifndef HAS_MSVC_2005_ISO_RTL",
    "#define HAS_MSVC_2005_ISO_RTL     0",
    "#endif",
    "",
    "#if HAS_MSVC_2005_ISO_RTL",
    "#pragma warning(disable : 4996)",
    "/* Or just turn off warnings about the newly deprecated CRT functions. */",
    "#ifndef _CRT_SECURE_NO_DEPRECATE",
    "#define _CRT_SECURE_NO_DEPRECATE",
    "#endif",
    "#ifndef _CRT_NONSTDC_NO_DEPRECATE",
    "#define _CRT_NONSTDC_NO_DEPRECATE",
    "#endif",
    "#define _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES     1",
    "#endif",
    "#endif",
    "/* [/i_a] */",
    "",
    "",
    "",
    "",
    "#include <stdio.h>",
    "#include <stdlib.h>",
    "#include <stdarg.h>",
    "#include <string.h>",
    "",
    "/* [i_a] MSVC doesn't define TRUE in the expected places; do it here to make sure we got it 'right' */",
    "#ifndef TRUE",
    "  #undef FALSE",
    "  #undef TRUE",
    "",
    "  #define FALSE 0",
    "  #define TRUE (!FALSE)",
    "#endif",
    "",
    "typedef short int Yshort;",
    "",
    0
};

static char const * const tables[] =
{
    "#line 67 \"push.skeleton\"",
    "",
    "#ifdef __cplusplus",
    "#ifndef _YACC_EXTERN_",
    "#define _YACC_EXTERN_ \"C\"",
    "#endif",
    "#endif",
    "",
    "extern _YACC_EXTERN_ Yshort yylhs[];",
    "extern _YACC_EXTERN_ Yshort yylen[];",
    "",
    "/* idx: current state; entry: non-zero if to reduce regardless of lookahead */",
    "extern _YACC_EXTERN_ Yshort yydefred[];",
    "",
    "extern _YACC_EXTERN_ Yshort yydgoto[];",
    "",
    "/* idx: current state; entry: non-zero if shifting|reducing possible",
    "   in this state - in that case, yycheck[entry + lookahead] indicates",
    "   whether to perform the action for this lookahead. */",
    "extern _YACC_EXTERN_ Yshort yysindex[];",
    "extern _YACC_EXTERN_ Yshort yyrindex[];",
    "",
    "/* yycindex idx: current state; entry: non-zero if shift/reduce",
    "   conflicts for this state - in that case, yycheck[entry + lookahead]",
    "   indicates whether there's a conflict for this lookahead */",
    "extern _YACC_EXTERN_ Yshort yycindex[];",
    "extern _YACC_EXTERN_ Yshort yycheck[];",
    "",
    "extern _YACC_EXTERN_ Yshort yygindex[];",
    "extern _YACC_EXTERN_ Yshort yytable[];",
    "extern _YACC_EXTERN_ Yshort yyctable[];",
    "",
    "#if YYDEBUG",
    "/* idx: token code; entry: spelling of token */",
    "extern _YACC_EXTERN_ char const *yyname[];",
    "",
    "extern _YACC_EXTERN_ char const *yyrule[];",
    "#endif",
    "",
    0
};

static char const * const header[] =
{
    "#line 106 \"push.skeleton\"",
    "",
    "#ifndef YYERRCODE",
    "#error Make sure you '#include' the generated btyacc .h headerfile in the .Y file itself, as it defines YYERRCODE and several other constants.",
    "#endif",
    "",
    "/* If delete function is not defined by the user, do not delete. */",
    "#ifndef YYDELETEVAL",
    "#define YYDELETEVAL(v, t)",
    "#endif",
    "",
    "#define YYEMPTY      (-1)",
    "#define yyclearin    (yychar = YYEMPTY)",
    "",
    "#define yyerrok      (yyps->errflag = 0)",
    "",
    "",
    "#ifndef YYSTACKGROWTH",
    "#define YYSTACKGROWTH 32",
    "#endif",
    "",
    "#ifndef YYDEFSTACKSIZE",
    "#define YYDEFSTACKSIZE 12",
    "#endif",
    "",
    "#ifndef YYLEXDEFSTACKSIZE",
    "#define YYLEXDEFSTACKSIZE (32 > YYSTACKGROWTH ? 32 : YYSTACKGROWTH)",
    "#endif",
    "",
    "#ifndef YYTRIALSTACKGROWTH",
    "#define YYTRIALSTACKGROWTH (4 > YYSTACKGROWTH ? 4 : YYSTACKGROWTH)",
    "#endif",
    "",
    "",
    "#ifdef YYDEBUG",
    "int yydebug = 0;",
    "#endif",
    "",
    "struct YYParseState_s",
    "{",
    "  struct YYParseState_s *save; /* Previously saved parser state */",
    "  int           state;",
    "  int           errflag;",
    "  Yshort       *ssp;         /* state stack pointer */",
    "  YYSTYPE      *vsp;         /* value stack pointer */",
    "  YYSTYPE       val;         /* value as returned by actions */",
    "  Yshort       *ss;          /* state stack base */",
    "  YYSTYPE      *vs;          /* values stack base */",
    "  int           lexeme;      /* index of the conflict lexeme in the lexical queue */",
    "  unsigned int  stacksize;   /* current maximum stack size */",
    "  Yshort        ctry;        /* index in yyctable[] for this conflict */",
    "};",
    "typedef struct YYParseState_s YYParseState;",
    "",
    "static YYParseState *yypstate = 0;",
    "",
    "/* yypath != NULL: do the full parse, starting at *yypath parser state. */",
    "static YYParseState *yypath = 0;",
    "",
    "/* Base of the lexical value queue */",
    "static YYSTYPE *yylvals = 0;",
    "",
    "/* Current position at lexical value queue */",
    "static YYSTYPE *yylvp = 0;",
    "",
    "/* End position of lexical value queue */",
    "static YYSTYPE *yylve = 0;",
    "",
    "/* The last allocated position at the lexical value queue */",
    "static YYSTYPE *yylvlim = 0;",
    "",
    "",
    "/* Current position at lexical token queue */",
    "static Yshort *yylexp = 0;",
    "",
    "static Yshort *yylexemes = 0;",
    "",
    "/* For use in generated program */",
    "#define yytrial (yypstate->save)",
    "#define yyerrflag (yypstate->errflag)",
    "#define yyssp (yypstate->ssp)",
    "#define yyvsp (yypstate->vsp)",
    "#define yyval (yypstate->val)",
    "#define yyss (yypstate->ss)",
    "#define yyvs (yypstate->vs)",
    "#define yystacksize (yypstate->stacksize)",
    "",
    "",
    "",
    "extern int yylex(void);",
    "",
    "",
    "/* Local prototypes. */",
    "int yyparse(void);",
    "",
    "",
    "#ifdef __cplusplus",
    "static void yySCopy(YYSTYPE *to, YYSTYPE *from, int size);",
    "#else",
    "#define yySCopy(to, from, size)         memcpy(to, from, (size) * sizeof((to)[0]))",
    "#endif",
    "",
    "",
    0
};

static char const * const body[] =
{
    "#line 209 \"push.skeleton\"",
    "",
    "#ifndef YYNEWSTATE",
    "static struct yyparsestate *YYNEWSTATE(int size)",
    "{",
    "    struct yyparsestate *p;",
    "",
    "#ifndef __cplusplus",
    "    p = (struct yyparsestate *)malloc(sizeof(struct yyparsestate));",
    "    p->stacksize = size+4;",
    "    p->ss = (short *)malloc((size+4)*sizeof(short));",
    "    p->vs = (YYSTYPE *)malloc((size+4)*sizeof(YYSTYPE));",
    "#else /* C++ */",
    "    p = new yyparsestate;",
    "    p->stacksize = size+4;",
    "    p->ss = new short[size + 4];",
    "    p->vs = new YYSTYPE[size + 4];",
    "#endif /* C++ */",
    "    return p;",
    "}",
    "#endif /* YYNEWSTATE */",
    "",
    "#ifndef YYFREESTATE",
    "#ifndef __cplusplus",
    "#define YYFREESTATE(p) (free((p)->ss), free((p)->vs), free(p))",
    "#else /* C++ */",
    "#define YYFREESTATE(p) (delete[] (p)->ss, delete[] (p)->vs, delete (p))",
    "#endif /* C++ */",
    "#endif /* YYFREESTATE */",
    "",
    "",
    "#define YYABORT goto yyabort",
    "#define YYACCEPT goto yyaccept",
    "#define YYERROR goto yyerrlab",
    "#define YYVALID                                             \\",
    "    do                                                      \\",
    "    {                                                       \\",
    "        if (yytrial)                                        \\",
    "            goto yyvalid;                                   \\",
    "    } while(0)",
    "",
    "int yyparse(int yychar, YYSTYPE yylval)",
    "{",
    "    int yym, yyn, yynewerrflag;",
    "    int unsigned yystate;",
    "#if YYDEBUG",
    "    char *yys;",
    "#endif",
    "",
    "    if (yychar < 0)",
    "        yychar = 0;",
    "    if (!yypstate)",
    "    {",
    "        /* initialize the parser state */",
    "        yypstate = YYNEWSTATE(12);",
    "        yypath = 0;",
    "        yytrial = 0;",
    "        yyerrflag = 0;",
    "        yylvp = yylve = yylvals;",
    "        yylexp = yylexemes;",
    "        yyssp = yyss;",
    "        yyvsp = yyvs;",
    "        *yyssp = yypstate->state = 0;",
    "    }",
    "    yystate = yypstate->state;",
    "#if YYDEBUG",
    "    if (yydebug)",
    "    {",
    "        yys = 0;",
    "        if (yychar <= YYMAXTOKEN)",
    "            yys = yyname[yychar];",
    "        if (!yys)",
    "            yys = \"illegal-symbol\";",
    "        printf(\"yydebug: state %d, input %d (%s) \", yystate,",
    "                yychar, yys);",
    "#ifdef YYDBPR",
    "        printf(\"<\");",
    "        YYDBPR(yylval);",
    "        printf(\">\");",
    "#endif",
    "        printf(\"\\n\");",
    "    }",
    "#endif",
    "    if (yystate == YYFINAL && yychar == 0)",
    "        goto yyaccept;",
    "    if (yytrial)",
    "    {",
    "        if (yylvp == yylvlim)",
    "            yyexpand();",
    "        *yylvp++ = yylval;",
    "        yylve++;",
    "        *yylexp++ = yychar;",
    "    }",
    "yyloop:",
    "    if ((yyn = yydefred[yystate]))",
    "        goto yyreduce;",
    "    if (yychar < 0)",
    "    {",
    "        if (yylvp < yylve)",
    "        {",
    "            yylval = *yylvp++;",
    "            yychar = *yylexp++;",
    "        }",
    "        else",
    "        {",
    "            yypstate->state = yystate;",
    "            return 0;",
    "        }",
    "#if YYDEBUG",
    "        if (yydebug)",
    "        {",
    "            yys = 0;",
    "            if (yychar <= YYMAXTOKEN)",
    "                yys = yyname[yychar];",
    "            if (!yys)",
    "                yys = \"illegal-symbol\";",
    "            printf(\"yydebug: state %d, reading %d (%s) \", yystate,",
    "                    yychar, yys);",
    "#ifdef YYDBPR",
    "            printf(\"<\");",
    "            YYDBPR(yylval);",
    "            printf(\">\");",
    "#endif",
    "            printf(\"\\n\");",
    "        }",
    "#endif",
    "    }",
    "    if ((yyn = yycindex[yystate]) &&",
    "        (yyn += yychar) >= 0 &&",
    "        yyn <= YYTABLESIZE &&",
    "        yycheck[yyn] == yychar)",
    "    {",
    "        int ctry;",
    "        struct yyparsestate *save;",
    "#if YYDEBUG",
    "        if (yydebug)",
    "            printf(\"yydebug: state %d, conflict%s\\n\", yystate,",
    "               yypath ? \", following successful trial parse\" :",
    "                   yytrial ? \"\" : \", starting trial parse\");",
    "#endif",
    "        if (yypath)",
    "        {",
    "            save = yypath;",
    "            yypath = save->save;",
    "            ctry = save->ctry;",
    "            if (save->state != yystate)",
    "                goto yyabort;",
    "            YYFREESTATE(save);",
    "        }",
    "        else",
    "        {",
    "            save = YYNEWSTATE(yyssp - yyss);",
    "            save->save = yypstate->save;",
    "            save->state = yystate;",
    "            save->errflag = yypstate->errflag;",
    "            save->ssp = save->ss + (yyssp - yyss);",
    "            save->vsp = save->vs + (yyvsp - yyvs);",
    "            memcpy(save->ss, yyss, (yyssp - yyss + 1)*sizeof(short));",
    "            YYSCOPY(save->vs, yyvs, yyssp - yyss + 1);",
    "            ctry = yytable[yyn];",
    "            if (yyctable[ctry] == -1)",
    "            {",
    "#if YYDEBUG",
    "                if (yydebug && yychar >= 0)",
    "                    printf(\"yydebug: backtracking 1 token\\n\");",
    "#endif",
    "                ctry++;",
    "            }",
    "            save->ctry = ctry;",
    "            if (!yytrial)",
    "            {",
    "                if (!yylexemes)",
    "                {",
    "#ifndef __cplusplus",
    "                    yylexemes = (short *)malloc(16*sizeof(short));",
    "                    yylvals = (YYSTYPE *)malloc(16*sizeof(YYSTYPE));",
    "#else  /* C++ */",
    "                    yylexemes = new short[16];",
    "                    yylvals = new YYSTYPE[16];",
    "#endif /* C++ */",
    "                    yylvlim = yylvals + 16;",
    "                }",
    "                if (yylvp == yylve)",
    "                {",
    "                    yylvp = yylve = yylvals;",
    "                    yylexp = yylexemes;",
    "                    if (yychar >= 0)",
    "                    {",
    "                        *yylve++ = yylval;",
    "                        *yylexp = yychar;",
    "                        yychar = -1;",
    "                    }",
    "                }",
    "            }",
    "            if (yychar >= 0)",
    "            {",
    "                yylvp--;",
    "        yylexp--;",
    "                yychar = -1;",
    "            }",
    "            save->lexeme = yylvp - yylvals;",
    "            yypstate->save = save;",
    "        }",
    "        if (yytable[yyn] == ctry)",
    "        {",
    "#if YYDEBUG",
    "            if (yydebug)",
    "                printf(\"yydebug: state %d, shifting to state %d\\n\",",
    "                    yystate, yyctable[ctry]);",
    "#endif",
    "            if (yychar < 0)",
    "            {",
    "                yylvp++;",
    "        yylexp++;",
    "        }",
    "            yychar = -1;",
    "            if (yyerrflag > 0)",
    "                --yyerrflag;",
    "            yystate = yyctable[ctry];",
    "            goto yyshift;",
    "        }",
    "        else",
    "        {",
    "            yyn = yyctable[ctry];",
    "            goto yyreduce;",
    "        }",
    "    }",
    "    if ((yyn = yysindex[yystate]) &&",
    "        (yyn += yychar) >= 0 &&",
    "        yyn <= YYTABLESIZE &&",
    "        yycheck[yyn] == yychar)",
    "    {",
    "#if YYDEBUG",
    "        if (yydebug)",
    "            printf(\"yydebug: state %d, shifting to state %d\\n\",",
    "                yystate, yytable[yyn]);",
    "#endif",
    "        yychar = (-1);",
    "        if (yyerrflag > 0)",
    "            --yyerrflag;",
    "        yystate = yytable[yyn];",
    "yyshift:",
    "        if (yyssp >= yyss + yystacksize - 1)",
    "            YYMORESTACK;",
    "        *++yyssp = yystate;",
    "        *++yyvsp = yylval;",
    "        goto yyloop;",
    "    }",
    "    if ((yyn = yyrindex[yystate]) &&",
    "        (yyn += yychar) >= 0 &&",
    "        yyn <= YYTABLESIZE &&",
    "        yycheck[yyn] == yychar)",
    "    {",
    "        yyn = yytable[yyn];",
    "        goto yyreduce;",
    "    }",
    "    if (yyerrflag)",
    "        goto yyinrecovery;",
    "    yynewerrflag = 1;",
    "    goto yyerrhandler;",
    "",
    "yyerrlab:",
    "    yynewerrflag = 0;",
    "yyerrhandler:",
    "    while (yytrial)",
    "    {",
    "        int ctry;",
    "        struct yyparsestate *save;",
    "",
    "#if YYDEBUG",
    "        if (yydebug)",
    "            printf(\"yydebug: error in state %d, %s state %d, %d tokens\\n\",",
    "               yystate, \"backtracking to\", yypstate->save->state,",
    "               (int)(yylvp - yylvals - yypstate->save->lexeme));",
    "#endif",
    "        save = yypstate->save;",
    "        yylvp = yylvals + save->lexeme;",
    "        yylexp = yylexemes + save->lexeme;",
    "        yychar = -1;",
    "        yyssp = yyss + (save->ssp - save->ss);",
    "        yyvsp = yyvs + (save->vsp - save->vs);",
    "        memcpy(yyss, save->ss, (yyssp - yyss + 1) * sizeof(short));",
    "        YYSCOPY(yyvs, save->vs, yyvsp - yyvs + 1);",
    "        ctry = ++save->ctry;",
    "        yystate = save->state;",
    "        if ((yyn = yyctable[ctry]) >= 0)",
    "            goto yyreduce;",
    "        yypstate->save = save->save;",
    "        YYFREESTATE(save);",
    "#if YYDEBUG",
    "        if (yydebug && !yytrial)",
    "            printf(\"yydebug: trial parse failed, entering error mode\\n\");",
    "#endif",
    "        yynewerrflag = 1;",
    "    }",
    "    if (yynewerrflag)",
    "        yyerror(\"syntax error\");",
    "yyinrecovery:",
    "    if (yyerrflag < 3)",
    "    {",
    "        yyerrflag = 3;",
    "        for (;;)",
    "        {",
    "            if ((yyn = yysindex[*yyssp]) && (yyn += YYERRCODE) >= 0 &&",
    "                yyn <= YYTABLESIZE && yycheck[yyn] == YYERRCODE)",
    "            {",
    "#if YYDEBUG",
    "                if (yydebug)",
    "                    printf(\"yydebug: state %d, error recovery %s state %d\\n\",",
    "                       *yyssp, \"shifting to\", yytable[yyn]);",
    "#endif",
    "                yystate = yytable[yyn];",
    "                goto yyshift;",
    "            }",
    "            else",
    "            {",
    "#if YYDEBUG",
    "                if (yydebug)",
    "                    printf(\"yydebug: error recovery discarding state %d\\n\",",
    "                        *yyssp);",
    "#endif",
    "                if (yyssp <= yyss)",
    "                    goto yyabort;",
    "                --yyssp;",
    "                --yyvsp;",
    "            }",
    "        }",
    "    }",
    "    else",
    "    {",
    "        if (yychar == 0)",
    "            goto yyabort;",
    "#if YYDEBUG",
    "        if (yydebug)",
    "        {",
    "            yys = 0;",
    "            if (yychar <= YYMAXTOKEN)",
    "                yys = yyname[yychar];",
    "            if (!yys)",
    "                yys = \"illegal-symbol\";",
    "            printf(\"yydebug: state %d, error recovery discards token %d (%s)\\n\",",
    "                    yystate, yychar, yys);",
    "        }",
    "#endif",
    "        yychar = (-1);",
    "        goto yyloop;",
    "    }",
    "yyreduce:",
    "    yym = yylen[yyn];",
    "#if YYDEBUG",
    "    if (yydebug)",
    "    {",
    "        printf(\"yydebug: state %d, reducing by rule %d (%s) \",",
    "            yystate, yyn, yyrule[yyn]);",
    "#ifdef YYDBPR",
    "        if (yym)",
    "        {",
    "            int i;",
    "            printf(\"<\");",
    "            for (i=yym; i>0; i--)",
    "            {",
    "                if (i!=yym)",
    "                    printf(\", \");",
    "                YYDBPR(yyvsp[1-i]);",
    "            }",
    "            printf(\">\");",
    "        }",
    "#endif",
    "        printf(\"\\n\");",
    "    }",
    "#endif",
    "    if (yyssp + 1 - yym >= yyss + yystacksize)",
    "        YYMORESTACK;",
    "    yyval = yyvsp[1-yym];",
    "    switch (yyn)",
    "    {",
    "",
    0
};

static char const * const trailer[] =
{
    "#line 586 \"push.skeleton\"",
    "",
    "    }",
    "",
    "#if YYDEBUG",
    "#if defined(YYDBPR)",
    "    if (yydebug)",
    "    {",
    "        printf(\"yydebug: after reduction, result is \");",
    "        YYDBPR(yyval);",
    "        printf(\"\\n\");",
    "    }",
    "#endif",
    "#endif",
    "    yyssp -= yym;",
    "    yystate = *yyssp;",
    "    yyvsp -= yym;",
    "    yym = yylhs[yyn];",
    "    if (yystate == 0 && yym == 0)",
    "    {",
    "#if YYDEBUG",
    "        if (yydebug)",
    "            printf(\"yydebug: after reduction, %s from state 0 to state %d\\n\",",
    "                   \"shifting\", YYFINAL);",
    "#endif",
    "        yystate = YYFINAL;",
    "        *++yyssp = YYFINAL;",
    "        *++yyvsp = yyval;",
    "        if (yychar == 0)",
    "            goto yyaccept;",
    "        goto yyloop;",
    "    }",
    "    if ((yyn = yygindex[yym]) && (yyn += yystate) >= 0 &&",
    "        yyn <= YYTABLESIZE && yycheck[yyn] == yystate)",
    "        yystate = yytable[yyn];",
    "    else",
    "        yystate = yydgoto[yym];",
    "#if YYDEBUG",
    "    if (yydebug)",
    "        printf(\"yydebug: after reduction, %s from state %d to state %d\\n\",",
    "               \"shifting\", *yyssp, yystate);",
    "#endif",
    "    if (yyssp >= yyss + yystacksize - 1)",
    "        YYMORESTACK;",
    "    *++yyssp = yystate;",
    "    *++yyvsp = yyval;",
    "    goto yyloop;",
    "",
    "yyvalid:",
    "    if (yypath)",
    "        goto yyabort;",
    "    while (yypstate->save)",
    "    {",
    "        struct yyparsestate *save = yypstate->save;",
    "        yypstate->save = save->save;",
    "        save->save = yypath;",
    "        yypath = save;",
    "    }",
    "#if YYDEBUG",
    "    if (yydebug)",
    "        printf(\"yydebug: trial successful, %s state %d, %d tokens\\n\",",
    "               \"backtracking to\", yypath->state,",
    "               (int)(yylvp - yylvals - yypath->lexeme));",
    "#endif",
    "    yychar = -1;",
    "    yyssp = yyss + (yypath->ssp - yypath->ss);",
    "    yyvsp = yyvs + (yypath->vsp - yypath->vs);",
    "    memcpy(yyss, yypath->ss, (yyssp - yyss + 1) * sizeof(short));",
    "    YYSCOPY(yyvs, yypath->vs, yyvsp - yyvs + 1);",
    "    yylvp = yylvals + yypath->lexeme;",
    "    yylexp = yylexemes + yypath->lexeme;",
    "    yystate = yypath->state;",
    "    goto yyloop;",
    "",
    "yyabort:",
    "    while (yypstate)",
    "    {",
    "        struct yyparsestate *save = yypstate;",
    "        yypstate = save->save;",
    "        YYFREESTATE(save);",
    "    }",
    "    while (yypath)",
    "    {",
    "        struct yyparsestate *save = yypath;",
    "        yypath = save->save;",
    "        YYFREESTATE(save);",
    "    }",
    "    return -1;",
    "",
    "yyaccept:",
    "    if (yytrial)",
    "        goto yyvalid;",
    "    while (yypstate)",
    "    {",
    "        struct yyparsestate *save = yypstate;",
    "        yypstate = save->save;",
    "        YYFREESTATE(save);",
    "    }",
    "    while (yypath)",
    "    {",
    "        struct yyparsestate *save = yypath;",
    "        yypath = save->save;",
    "        YYFREESTATE(save);",
    "    }",
    "    return 1;",
    "}",
    "",
    "",
    "/* Call yylex() unless the token has already been read. */",
    "static int yyLex1(void)",
    "{",
    "  if (yylvp < yylve)",
    "  {",
    "    /* we're currently re-reading tokens */",
    "    yylval = *yylvp++;",
    "    return *yylexp++;",
    "  }",
    "  else if (yytrial)",
    "  {",
    "    /* in trial mode; save scanner results for future parse attempts */",
    "    if (yylvp == yylvlim)",
    "      yyExpand();",
    "    *yylexp = yylex();",
    "    *yylvp++ = yylval;",
    "    ++yylve;",
    "    ++yylpe;",
    "    return *yylexp++;",
    "  }",
    "  else",
    "  {",
    "    /* normal operation, no conflict encountered */",
    "    return yylex();",
    "  }",
    "}",
    "",
    "/* Enlarge lexical value queue */",
    "static int yyexpand(void)",
    "{",
    "    int p = yylvp-yylvals;",
    "    int s = yylvlim-yylvals;",
    "",
    "    s += 16;",
    "#ifndef __cplusplus",
    "    yylvals = (YYSTYPE *)realloc(yylvals, s*sizeof(YYSTYPE));",
    "    yylexemes = (short *)realloc(yylexemes, s*sizeof(short));",
    "#else /* C++ */",
    "    {",
    "        short *tl = yylexemes;",
    "        YYSTYPE *tv = yylvals;",
    "        yylvals = new YYSTYPE[s];",
    "        yylexemes = new short[s];",
    "        memcpy(yylexemes, tl, (s-16)*sizeof(short));",
    "        YYSCOPY(yylvals, tv, s-16);",
    "        delete[] tl;",
    "        delete[] tv;",
    "    }",
    "#endif /* C++ */",
    "    yylvp = yylve = yylvals + p;",
    "    yylvlim = yylvals + s;",
    "    yylexp = yylexemes + p;",
    "    return 0;",
    "}",
    "static int yyExpand(void)",
    "{",
    "  int p = yylvp - yylvals;",
    "  int s = yylvlim - yylvals;",
    "  s += YYSTACKGROWTH;",
    "  {",
    "    Yshort  *tl = yylexemes;",
    "    YYSTYPE *tv = yylvals;",
    "#ifdef __cplusplus",
    "    yylvals = new YYSTYPE[s];",
    "    yylexemes = new Yshort[s];",
    "#else",
    "    yylvals = (YYSTYPE*)malloc(s * sizeof(yylvals[0]));",
    "    yylexemes = (Yshort*)malloc(s * sizeof(yylexemes[0]));",
    "#endif",
    "    memcpy(yylexemes, tl, (s - YYSTACKGROWTH) * sizeof(yylexemes[0]));",
    "    yySCopy(yylvals, tv, s - YYSTACKGROWTH);",
    "#ifdef __cplusplus",
    "    delete[] tl;",
    "    delete[] tv;",
    "#else",
    "    free(tl);",
    "    free(tv);",
    "#endif",
    "  }",
    "  yylvp = yylve = yylvals + p;",
    "  yylvlim = yylvals + s;",
    "  yylpp = yylpe = yylpsns + p;",
    "  yylplim = yylpsns + s;",
    "  yylexp = yylexemes + p;",
    "  return 0;",
    "}",
    "",
    "#ifdef __cplusplus",
    "",
    "static void yySCopy(YYSTYPE *to, YYSTYPE *from, int size)",
    "{",
    "  int i;",
    "  for (i = size - 1; i >= 0; --i)",
    "  {",
    "    to[i] = from[i];",
    "  }",
    "}",
    "",
    "#endif",
    "",
    "static void yyMoreStack(YYParseState *yyps)",
    "{",
    "  int p = yyps->ssp - yyps->ss;",
    "  Yshort  *tss = yyps->ss;",
    "  YYSTYPE *tvs = yyps->vs;",
    "#ifdef __cplusplus",
    "  yyps->ss = new Yshort [yyps->stacksize + YYSTACKGROWTH];",
    "  yyps->vs = new YYSTYPE[yyps->stacksize + YYSTACKGROWTH];",
    "#else",
    "  yyps->ss = (Yshort*)malloc(sizeof(yyps->ss[0]) * (yyps->stacksize + YYSTACKGROWTH));",
    "  yyps->vs = (YYSTYPE*)malloc(sizeof(yyps->vs[0]) * (yyps->stacksize + YYSTACKGROWTH));",
    "#endif",
    "  memcpy(yyps->ss, tss, yyps->stacksize * sizeof(yyps->ss[0]));",
    "  yySCopy(yyps->vs, tvs, yyps->stacksize);",
    "  yyps->stacksize += YYSTACKGROWTH;",
    "#ifdef __cplusplus",
    "  delete[] tss;",
    "  delete[] tvs;",
    "#else",
    "  free(tss);",
    "  free(tvs);",
    "#endif",
    "  tss = 0;",
    "  tvs = 0;",
    "  yyps->ssp = yyps->ss + p;",
    "  yyps->vsp = yyps->vs + p;",
    "  yyps->psp = yyps->ps + p;",
    "#if YYDEBUG",
    "  if (yydebug)",
    "  {",
    "    BTYACC_DEBUG_LOG_EOL(\"btyacc: stack size increased to %d\\n\", yyps->stacksize);",
    "  }",
    "#endif",
    "}",
    "",
    "",
    "static YYParseState *yyNewState(int old_size, int growth)",
    "{",
    "  YYParseState *p;",
    "  int size = old_size + growth;",
    "",
    "#ifdef __cplusplus",
    "  p = new YYParseState;",
    "  p->ss = new Yshort [size];",
    "  p->vs = new YYSTYPE[size];",
    "",
    "  /*",
    "   * C++: YYSTYPE can be an arbitrary class, so we need to",
    "   *      explicitly zero it",
    "   *",
    "   * However, keep in mind that the caller of this function will fill the items",
    "   * up to index [old_size] (not including that one)!",
    "   */",
    "  for (int i = old_size; i < size; i++)",
    "  {",
    "      YYSTYPE_ZERO(p->vs[i]);",
    "  }",
    "#else",
    "  p = (YYParseState*)malloc(sizeof(p[0]));",
    "  p->ss = (Yshort*) malloc(size * sizeof(p->ss[0]));",
    "  p->vs = (YYSTYPE*)malloc(size * sizeof(p->vs[0]));",
    "  /*",
    "   * Keep in mind that the caller of this function will fill the items",
    "   * up to index [old_size] (not including that one)!",
    "   */",
    "  memset(&p->vs[old_size], 0, (size - old_size) * sizeof(p->vs[0]));",
    "  memset(&p->ps[old_size], 0, (size - old_size) * sizeof(p->ps[0]));",
    "#endif",
    "  p->stacksize = size;",
    "  return p;",
    "}",
    "",
    "static void yyFreeState(YYParseState **v)",
    "{",
    "  YYParseState *p = *v;",
    "",
    "#ifdef __cplusplus",
    "  delete[] p->ss;",
    "  delete[] p->vs;",
    "  delete p;",
    "#else",
    "  free(p->ss);",
    "  free(p->vs);",
    "  free(p);",
    "#endif",
    "",
    "  *v = 0;",
    "}",
    "",
    "/*",
    " * ----------------------------------------------------------------------",
    " * Several functions which can be overridden by the user when she has set",
    " * up the proper #define's.",
    " *",
    " * Note:",
    " *",
    " * We assume that the compiler is smart enough to discard these local",
    " * functions when their references through the #define's have been",
    " * overridden.",
    " * ----------------------------------------------------------------------",
    " */",
    "",
    "static void btyacc_set_yydebug_from_env(void)",
    "{",
    "  const char *yys = getenv(\"YYDEBUG\");",
    "  char yyn;",
    "",
    "  if (yys)",
    "  {",
    "    yyn = *yys;",
    "    if (yyn >= '0' && yyn <= '9')",
    "      yydebug = yyn - '0';",
    "  }",
    "}",
    "",
    "static void btyacc_debug_log_start(const char *msg)",
    "{",
    "    fprintf(stderr, \"%s\", msg);",
    "}",
    "",
    "static void btyacc_debug_log_partial(const char *msg, ...)",
    "{",
    "    va_list args;",
    "",
    "    va_start(args, msg);",
    "    vfprintf(stderr, msg, args);",
    "    va_end(args);",
    "}",
    "",
    "static void btyacc_debug_log_eol(const char *msg, ...)",
    "{",
    "    va_list args;",
    "",
    "    va_start(args, msg);",
    "    vfprintf(stderr, msg, args);",
    "    va_end(args);",
    "}",
    "",
    0
};

static char const * const line_position[] =
{
    "#line 932 \"push.skeleton\"",
    "#line %d \"%s\"",
    "",
    0
};

static char const * const comment_start[] =
{
    "#line 935 \"push.skeleton\"",
    "/*",
    0
};

static char const * const comment_end[] =
{
    "#line 937 \"push.skeleton\"",
    "*/",
    0
};

static char const * const action_case_start[] =
{
    "#line 939 \"push.skeleton\"",
    "  case %d:",
    "",
    0
};

static char const * const action_code[] =
{
    "#line 942 \"push.skeleton\"",
    "    %s;",
    "",
    "",
    0
};

static char const * const action_case_end[] =
{
    "#line 946 \"push.skeleton\"",
    "    break;",
    "",
    "",
    0
};

static char const * const action_if_not_yytrial_start[] =
{
    "#line 950 \"push.skeleton\"",
    "if (!yytrial)",
    "",
    0
};

static char const * const action_block_start[] =
{
    "#line 953 \"push.skeleton\"",
    "{",
    0
};

static char const * const action_block_end[] =
{
    "#line 955 \"push.skeleton\"",
    "}",
    0
};

static char const * const yyval_tag_reference[] =
{
    "#line 957 \"push.skeleton\"",
    "yyval.%s",
    0
};

static char const * const yyval_reference[] =
{
    "#line 959 \"push.skeleton\"",
    "yyval",
    0
};

static char const * const yyvsp_tag_reference[] =
{
    "#line 961 \"push.skeleton\"",
    "yyvsp[%d].%s",
    0
};

static char const * const yyvsp_reference[] =
{
    "#line 963 \"push.skeleton\"",
    "yyvsp[%d]",
    0
};

static char const * const rflag_prefix[] =
{
    "#line 965 \"push.skeleton\"",
    "static",
    0
};

static char const * const not_rflag_prefix[] =
{
    "#line 967 \"push.skeleton\"",
    "",
    0
};

static char const * const int_table_start[] =
{
    "#line 969 \"push.skeleton\"",
    "%sYshort %29s[%5d] = {%5d%s",
    0
};

static char const * const int_table_entry[] =
{
    "#line 971 \"push.skeleton\"",
    "%5d%s",
    0
};

static char const * const int_table_entry_separator[] =
{
    "#line 973 \"push.skeleton\"",
    ",",
    0
};

static char const * const int_table_end[] =
{
    "#line 975 \"push.skeleton\"",
    "",
    "};",
    "",
    0
};

static char const * const table_size[] =
{
    "#line 979 \"push.skeleton\"",
    "",
    "",
    "#define YYTABLESIZE %d",
    "",
    "",
    "",
    0
};

static char const * const defines_file_protection_start[] =
{
    "#line 986 \"push.skeleton\"",
    "",
    "#ifndef _BTYACC_DEFINES_H_",
    "#define _BTYACC_DEFINES_H_",
    "",
    "",
    "",
    0
};

static char const * const defines_file_protection_end[] =
{
    "#line 993 \"push.skeleton\"",
    "",
    "",
    "#endif /* _BTYACC_DEFINES_H_ */",
    "",
    "",
    0
};

static char const * const token_charset[] =
{
    "#line 999 \"push.skeleton\"",
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_$",
    0
};

static char const * const define_token[] =
{
    "#line 1001 \"push.skeleton\"",
    "#define %-60s %5d",
    "",
    0
};

static char const * const yystype_extern_decl[] =
{
    "#line 1004 \"push.skeleton\"",
    "",
    "extern YYSTYPE yylval;",
    "",
    0
};

static char const * const define_default_yystype[] =
{
    "#line 1008 \"push.skeleton\"",
    "",
    "#ifndef YYSTYPE",
    "typedef int YYSTYPE;",
    "",
    "#ifdef __cplusplus",
    "#define YYSTYPE_ZERO(yylval)        yylval = 0",
    "#endif",
    "",
    "/*",
    " * Since we know the yylval type, we can also provide a default yydebug log function now:",
    " */",
    "#ifndef YYDBPR",
    "#define YYDBPR(yystype)    BTYACC_DEBUG_LOG_PARTIAL(\"%d\", (yystype))",
    "#endif",
    "#endif /* YYSTYPE */",
    "",
    "",
    0
};

static char const * const union_decl_start[] =
{
    "#line 1026 \"push.skeleton\"",
    "",
    "typedef union",
    0
};

static char const * const union_decl_end[] =
{
    "#line 1029 \"push.skeleton\"",
    " yystype_t;",
    "#define YYSTYPE yystype_t",
    "",
    "",
    0
};

static char const * const define_yymaxtoken[] =
{
    "#line 1034 \"push.skeleton\"",
    "",
    "#define YYMAXTOKEN %5d",
    "",
    "",
    0
};

static char const * const define_yyfinal[] =
{
    "#line 1039 \"push.skeleton\"",
    "",
    "#define YYFINAL %5d",
    "",
    "",
    0
};

static char const * const define_yydebug[] =
{
    "#line 1044 \"push.skeleton\"",
    "",
    "#ifndef YYDEBUG",
    "#define YYDEBUG %d",
    "#endif",
    "",
    "",
    0
};

static char const * const debug_yy_null[] =
{
    "#line 1051 \"push.skeleton\"",
    "0",
    0
};

static char const * const debug_yyname_strings_start[] =
{
    "#line 1053 \"push.skeleton\"",
    "",
    "#if YYDEBUG",
    "%schar const *yyname[] = {",
    "",
    0
};

static char const * const debug_yyname_strings_separator[] =
{
    "#line 1058 \"push.skeleton\"",
    ",",
    0
};

static char const * const debug_yyname_strings_end[] =
{
    "#line 1060 \"push.skeleton\"",
    "};",
    "#endif",
    "",
    "",
    0
};

static char const * const debug_yyrule_strings_start[] =
{
    "#line 1065 \"push.skeleton\"",
    "",
    "#if YYDEBUG",
    "%schar const *yyrule[] = {",
    "",
    0
};

static char const * const debug_yyrule_strings_separator[] =
{
    "#line 1070 \"push.skeleton\"",
    ",",
    0
};

static char const * const debug_yyrule_strings_end[] =
{
    "#line 1072 \"push.skeleton\"",
    "};",
    "#endif",
    "",
    "",
    0
};

static char const * const DEFINES_FILENAME[] =
{
    "#line 1077 \"push.skeleton\"",
    "%s%s.tab.h",
    0
};

static char const * const OUTPUT_FILENAME[] =
{
    "#line 1079 \"push.skeleton\"",
    "%s%s.tab.c",
    0
};

static char const * const CODE_FILENAME[] =
{
    "#line 1081 \"push.skeleton\"",
    "%s%s.code.c",
    0
};

static char const * const VERBOSE_FILENAME[] =
{
    "#line 1083 \"push.skeleton\"",
    "%s%s.output",
    0
};

struct section section_list_push[] = {
	{ "language", &language[0] },
	{ "banner", &banner[0] },
	{ "tables", &tables[0] },
	{ "header", &header[0] },
	{ "body", &body[0] },
	{ "trailer", &trailer[0] },
	{ "line_position", &line_position[0] },
	{ "comment_start", &comment_start[0] },
	{ "comment_end", &comment_end[0] },
	{ "action_case_start", &action_case_start[0] },
	{ "action_code", &action_code[0] },
	{ "action_case_end", &action_case_end[0] },
	{ "action_if_!yytrial_start", &action_if_not_yytrial_start[0] },
	{ "action_block_start", &action_block_start[0] },
	{ "action_block_end", &action_block_end[0] },
	{ "yyval.tag_reference", &yyval_tag_reference[0] },
	{ "yyval_reference", &yyval_reference[0] },
	{ "yyvsp.tag_reference", &yyvsp_tag_reference[0] },
	{ "yyvsp_reference", &yyvsp_reference[0] },
	{ "rflag_prefix", &rflag_prefix[0] },
	{ "!rflag_prefix", &not_rflag_prefix[0] },
	{ "int_table_start", &int_table_start[0] },
	{ "int_table_entry", &int_table_entry[0] },
	{ "int_table_entry_separator", &int_table_entry_separator[0] },
	{ "int_table_end", &int_table_end[0] },
	{ "table_size", &table_size[0] },
	{ "defines_file_protection_start", &defines_file_protection_start[0] },
	{ "defines_file_protection_end", &defines_file_protection_end[0] },
	{ "token_charset", &token_charset[0] },
	{ "define_token", &define_token[0] },
	{ "yystype_extern_decl", &yystype_extern_decl[0] },
	{ "define_default_yystype", &define_default_yystype[0] },
	{ "union_decl_start", &union_decl_start[0] },
	{ "union_decl_end", &union_decl_end[0] },
	{ "define_yymaxtoken", &define_yymaxtoken[0] },
	{ "define_yyfinal", &define_yyfinal[0] },
	{ "define_yydebug", &define_yydebug[0] },
	{ "debug_yy_null", &debug_yy_null[0] },
	{ "debug_yyname_strings_start", &debug_yyname_strings_start[0] },
	{ "debug_yyname_strings_separator", &debug_yyname_strings_separator[0] },
	{ "debug_yyname_strings_end", &debug_yyname_strings_end[0] },
	{ "debug_yyrule_strings_start", &debug_yyrule_strings_start[0] },
	{ "debug_yyrule_strings_separator", &debug_yyrule_strings_separator[0] },
	{ "debug_yyrule_strings_end", &debug_yyrule_strings_end[0] },
	{ "DEFINES_FILENAME", &DEFINES_FILENAME[0] },
	{ "OUTPUT_FILENAME", &OUTPUT_FILENAME[0] },
	{ "CODE_FILENAME", &CODE_FILENAME[0] },
	{ "VERBOSE_FILENAME", &VERBOSE_FILENAME[0] },
	{ 0, 0 } };

unsigned int section_list_push_count = 48;

